### ISSUE TITLE
Publish the package to npm?

### ISSUE THREAD

**Issue by sunnysingh** [mpd106/metalsmith-pretty-serve#1]
This package does not seem to be available through npm. I'm currently loading it locally. Also, is this package still maintained? I think it's the only available plugin for getting pretty URLs to work in Metalsmith (outside of folder/index.html hacks).

**Comment by mpd106** [comment]
Boy, am I sorry for the delay in getting back to you. npm'd: https://www.npmjs.com/package/metalsmith-pretty-serve

Still maintained, albeit intermittently. I use it for a couple of active projects :)

**Comment by sunnysingh** [comment]
@mpd106 Not a problem. I think I ended up using Browsersync's middleware but I'm sure someone else might find this package useful and easily installable now.
